spring:
  # elasticsearch 配置
  elasticsearch:
    username: elastic
    password: QmlsSThsJJx_UUVYx9Ro
    uris: http://localhost:9200

  application:
    name: lin-agent
  datasource:
    # mysql配置
    mysql:
      url: jdbc:mysql://localhost:3306/chat_agent
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    # pgVector配置
    pgvector:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver



  ai:
    # chatmemory不初始化schema
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
    # dashscope 配置
    dashscope:
      api-key: sk-6dc2d723f04249d4b8f203d8e43fdaa3
      chat:
        options:
          model: qwen3-max
    #vector
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000
    #mcp 服务配置
    mcp:
      client:
        stdio:
          servers-configuration: classpath:/mcp-servers.json
server:
  port: 8123
  servlet:
    context-path: /agent

#knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    group: 'default'
    paths-to-math: '/**'
    packages-to-scan: com.lin.linagent.controller
knife4j:
  enable: true
  setting:
    language: zh_cn


# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:

      logic-delete-field: isDelete #逻辑删除字段
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值